/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TableColumnResizerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  minColumnWidth: 50,
  maxColumnWidth: 500,
  defaultColumnWidth: 150,
  enableInPreviewMode: true
};
var TableColumnResizerPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.isResizing = false;
    this.currentTable = null;
    this.currentColumn = -1;
    this.startX = 0;
    this.startWidth = 0;
    this.handleMouseMove = (e) => {
      if (!this.isResizing || !this.currentTable)
        return;
      const deltaX = e.clientX - this.startX;
      let newWidth = this.startWidth + deltaX;
      newWidth = Math.max(
        this.settings.minColumnWidth,
        Math.min(newWidth, this.settings.maxColumnWidth)
      );
      const rows = this.currentTable.querySelectorAll("tr");
      rows.forEach((row) => {
        const cell = row.children[this.currentColumn];
        if (cell && cell.style) {
          cell.style.width = newWidth + "px";
          cell.style.minWidth = newWidth + "px";
          cell.style.maxWidth = newWidth + "px";
        }
      });
    };
    this.handleMouseUp = () => {
      if (!this.isResizing)
        return;
      this.isResizing = false;
      document.removeEventListener("mousemove", this.handleMouseMove);
      document.removeEventListener("mouseup", this.handleMouseUp);
      if (this.currentTable) {
        this.currentTable.removeAttribute("data-resizing");
        this.saveTableColumnWidths(this.currentTable);
      }
      document.body.classList.remove("table-resizing");
      this.currentTable = null;
      this.currentColumn = -1;
    };
  }
  async onload() {
    await this.loadSettings();
    console.log("\u52A0\u8F7D\u8868\u683C\u5217\u5BBD\u8C03\u6574\u63D2\u4EF6 (\u9884\u89C8\u6A21\u5F0F)");
    if (this.settings.enableInPreviewMode) {
      this.registerMarkdownPostProcessor((element, context) => {
        this.processTablesInPreview(element, context);
      });
    }
    this.addSettingTab(new TableColumnResizerSettingTab(this.app, this));
  }
  // 预览模式处理表格
  processTablesInPreview(element, context) {
    const tables = element.querySelectorAll("table");
    tables.forEach((table, index) => {
      this.makeTableResizable(table, index, context.sourcePath);
    });
  }
  // 使表格可调整列宽
  makeTableResizable(table, tableIndex, filePath) {
    if (table.hasAttribute("data-resizable"))
      return;
    table.setAttribute("data-resizable", "true");
    this.applySavedColumnWidths(table);
    const headers = table.querySelectorAll("th, td");
    headers.forEach((header, columnIndex) => {
      if (columnIndex === headers.length - 1)
        return;
      const headerEl = header;
      const resizer = document.createElement("div");
      resizer.className = "table-column-resizer";
      resizer.style.cssText = `
				position: absolute;
				right: -3px;
				top: 0;
				width: 6px;
				height: 100%;
				cursor: col-resize;
				z-index: 10;
				opacity: 0;
				transition: opacity 0.2s;
			`;
      headerEl.style.position = "relative";
      headerEl.appendChild(resizer);
      headerEl.addEventListener("mouseenter", () => {
        resizer.style.opacity = "1";
      });
      headerEl.addEventListener("mouseleave", () => {
        if (!this.isResizing)
          resizer.style.opacity = "0";
      });
      resizer.addEventListener("mousedown", (e) => {
        e.preventDefault();
        this.startResize(e, table, columnIndex);
      });
    });
  }
  startResize(e, table, columnIndex) {
    this.isResizing = true;
    this.currentTable = table;
    this.currentColumn = columnIndex;
    this.startX = e.clientX;
    const rows = table.querySelectorAll("tr");
    const firstCell = rows[0].children[columnIndex];
    this.startWidth = firstCell.offsetWidth;
    table.setAttribute("data-resizing", "true");
    document.body.classList.add("table-resizing");
    document.addEventListener("mousemove", this.handleMouseMove);
    document.addEventListener("mouseup", this.handleMouseUp);
  }
  // 保存表格列宽设置
  saveTableColumnWidths(table) {
    const tableId = this.getTableId(table);
    const rows = table.querySelectorAll("tr");
    if (rows.length === 0)
      return;
    const columnWidths = {};
    const firstRow = rows[0];
    for (let i = 0; i < firstRow.children.length; i++) {
      const cell = firstRow.children[i];
      if (cell.style.width) {
        columnWidths[i] = parseInt(cell.style.width);
      }
    }
    const savedData = this.loadDataSync();
    savedData[tableId] = columnWidths;
    this.saveData(savedData);
  }
  // 恢复保存的列宽设置
  applySavedColumnWidths(table) {
    const tableId = this.getTableId(table);
    const savedData = this.loadDataSync();
    const columnWidths = savedData[tableId];
    if (!columnWidths)
      return;
    Object.entries(columnWidths).forEach(([columnIndex, width]) => {
      const rows = table.querySelectorAll("tr");
      rows.forEach((row) => {
        const cell = row.children[parseInt(columnIndex)];
        if (cell && cell.style) {
          cell.style.width = width + "px";
          cell.style.minWidth = width + "px";
          cell.style.maxWidth = width + "px";
        }
      });
    });
  }
  // 生成表格唯一ID
  getTableId(table) {
    const content = table.textContent || "";
    const truncatedContent = content.substring(0, 50).replace(/\s/g, "");
    const parent = table.parentElement;
    const index = parent ? Array.from(parent.children).indexOf(table) : 0;
    return `table_${truncatedContent}_${index}`;
  }
  loadDataSync() {
    return this.loadData() || {};
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
    console.log("\u5378\u8F7D\u8868\u683C\u5217\u5BBD\u8C03\u6574\u63D2\u4EF6");
  }
};
var TableColumnResizerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u8868\u683C\u5217\u5BBD\u8C03\u6574\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u6700\u5C0F\u5217\u5BBD").setDesc("\u5217\u7684\u6700\u5C0F\u5BBD\u5EA6\uFF08\u50CF\u7D20\uFF09").addSlider((slider) => slider.setLimits(30, 100, 10).setValue(this.plugin.settings.minColumnWidth).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.minColumnWidth = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6700\u5927\u5217\u5BBD").setDesc("\u5217\u7684\u6700\u5927\u5BBD\u5EA6\uFF08\u50CF\u7D20\uFF09").addSlider((slider) => slider.setLimits(200, 800, 50).setValue(this.plugin.settings.maxColumnWidth).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxColumnWidth = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u9ED8\u8BA4\u5217\u5BBD").setDesc("\u65B0\u8868\u683C\u7684\u9ED8\u8BA4\u5217\u5BBD\uFF08\u50CF\u7D20\uFF09").addSlider((slider) => slider.setLimits(80, 300, 20).setValue(this.plugin.settings.defaultColumnWidth).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.defaultColumnWidth = value;
      await this.plugin.saveSettings();
    }));
  }
};
